main = ".open-next/worker.js"
name = "safecircle-waitlist"

route = { pattern = "app.safecircle.tech/*", zone_name = "safecircle.tech" }

compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[placement]
mode = "smart"






