main = ".open-next/worker.js"
name = "safecircle-waitlist"

route = { pattern = "app.safecircle.tech/*", zone_name = "safecircle.tech" }

compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 0.1

[placement]
mode = "smart"






